server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vcoolchen/aigou_config.git
          username: Vcoolchen
          password: 19970629aS
          #前台访问配置文件路径http://localhost:8848/application-plat-test.yml(github中命名 application-模块名-类型.yml)
